export const SET_GO_BACK_BUTTON = 'INSTR/ACTION/SET_GO_BACK_BUTTON';
export const SET_READY_BUTTON = 'INSTR/ACTION/SET_READY_BUTTON';

export const RESET_INSTRUCTION_STATES = 'INSTR/ACTION/RESET_INSTRUCTION_STATES';
