export const SET_REENTER = 'PASSWORD/ACTION/SET_REENTER';
export const SET_PATTERN = 'PASSWORD/ACTION/SET_PATTERN';
export const SET_CORRECT = 'PASSWORD/ACTION/SET_CORRECT';
export const SET_INCORRECT = 'PASSWORD/ACTION/SET_INCORRECT';
export const SET_REJECT_PARAM = 'PASSWORD/ACTION/SET_REJECT_PARAM';
export const SET_MISMATCH = 'PASSWORD/ACTION/SET_MISMATCH';
export const SET_INPUTS = 'PASSWORD/ACTION/SET_INPUTS';

export const RESET_PASSWORD_STATES = 'PASSWORD/ACTION/RESET_PASSWORD_STATES';
