export const SET_REENTER = 'PASSWORD/ACTION/SET_REENTER';
export const SET_PATTERN = 'PASSWORD/ACTION/SET_PATTERN';
export const SET_CORRECT = 'PASSWORD/ACTION/SET_CORRECT';
export const SET_INCORRECT = 'PASSWORD/ACTION/SET_INCORRECT';
