export const SAVE_INPUT = 'PREPARATION/ACTION/SAVE_INPUT';
export const TRY_CONNECT = 'PREPARATION/ACTION/TRY_CONNECT';
export const SET_CONNECTING = 'PREPARATION/ACTION/SET_CONNECTING';
export const SET_VERIFIED = 'PREPARATION/ACTION/SET_VERIFIED';
export const SET_CALIBRATION_COUNTDOWN =
  'PREPARATION/ACTION/SET_CALIBRATION_COUNTDOWN';
